from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')

s=s.replace("svg{width:100%;height:240px;border-left:1px solid #ddd;border-bottom:1px solid #ddd}","svg{width:100%;height:300px}",1)
s=s.replace('<svg id="chart" viewBox="0 0 600 240" preserveAspectRatio="none"></svg>','<svg id="chart" viewBox="0 0 640 300" preserveAspectRatio="xMidYMid meet"></svg>',1)
old="function show(id){const p=archive.find(x=>x.id===id),h=(p.history||[]).slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));mn.textContent=p.name;history.innerHTML=h.slice().reverse().map(x=>`<div class=\"hist\"><span>${dateDE(x.date)}</span><b>${euro(x.price)}</b></div>`).join('');let v=h.map(x=>+x.price),lo=Math.min(...v),hi=Math.max(...v);if(lo===hi){lo-=.5;hi+=.5}let X=i=>30+540*(h.length===1?.5:i/(h.length-1)),Y=x=>210-180*(x-lo)/(hi-lo);chart.innerHTML=`<polyline fill=\"none\" stroke=\"currentColor\" stroke-width=\"4\" points=\"${h.map((x,i)=>X(i)+','+Y(x.price)).join(' ')}\"/>`;modal.classList.add('open')}"
new="function show(id){const p=archive.find(x=>x.id===id),h=(p.history||[]).slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));mn.textContent=p.name;history.innerHTML=h.slice().reverse().map(x=>`<div class=\"hist\"><span>${dateDE(x.date)}</span><b>${euro(x.price)}</b></div>`).join('');if(!h.length){chart.innerHTML='';modal.classList.add('open');return}const W=640,H=300,L=68,R=18,T=28,B=58,pw=W-L-R,ph=H-T-B;let v=h.map(x=>+x.price),lo=Math.min(...v),hi=Math.max(...v),span=hi-lo;if(span===0)span=Math.max(.5,hi*.08||.5);lo=Math.max(0,lo-span*.15);hi=hi+span*.15;if(hi===lo)hi=lo+1;const X=i=>L+pw*(h.length===1?.5:i/(h.length-1)),Y=x=>T+ph*(1-(x-lo)/(hi-lo));const tickCount=4;let grid='';for(let i=0;i<=tickCount;i++){const val=lo+(hi-lo)*i/tickCount,y=Y(val);grid+=`<line x1=\"${L}\" y1=\"${y}\" x2=\"${W-R}\" y2=\"${y}\" stroke=\"#e5e7eb\" stroke-width=\"1\"/><text x=\"${L-8}\" y=\"${y+4}\" text-anchor=\"end\" font-size=\"12\" fill=\"#6b7280\">${euro(val)}</text>`}const step=Math.max(1,Math.ceil((h.length-1)/5));let dates='';h.forEach((x,i)=>{if(i===0||i===h.length-1||i%step===0)dates+=`<text x=\"${X(i)}\" y=\"${H-18}\" text-anchor=\"middle\" font-size=\"11\" fill=\"#6b7280\">${dateDE(x.date)}</text>`});const line=`<polyline fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linejoin=\"round\" stroke-linecap=\"round\" points=\"${h.map((x,i)=>X(i)+','+Y(+x.price)).join(' ')}\"/>`;const pts=h.map((x,i)=>{const px=X(i),py=Y(+x.price),ly=py<T+20?py+20:py-10;return `<circle cx=\"${px}\" cy=\"${py}\" r=\"5\" fill=\"currentColor\"><title>${dateDE(x.date)} · ${euro(x.price)}</title></circle><text x=\"${px}\" y=\"${ly}\" text-anchor=\"middle\" font-size=\"12\" font-weight=\"700\" fill=\"currentColor\">${euro(x.price)}</text>`}).join('');chart.innerHTML=`<line x1=\"${L}\" y1=\"${T}\" x2=\"${L}\" y2=\"${H-B}\" stroke=\"#9ca3af\"/><line x1=\"${L}\" y1=\"${H-B}\" x2=\"${W-R}\" y2=\"${H-B}\" stroke=\"#9ca3af\"/>${grid}${dates}${line}${pts}`;modal.classList.add('open')}"
if old not in s:
    raise SystemExit('chart function anchor not found')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('price chart axes and labels added')
