from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

# Recipe UI: use same household settings as the shopping list.
old='<section id="recipesView" class="hidden"><div class="recipe-intro"><h2>Rezepte aus aktuellen Angeboten</h2><div class="hint">Jedes Rezept verwendet ausschließlich aktuell gefundene Angebote aus genau einem Markt.</div><div class="markets" style="margin-top:12px"><button id="rREWE" class="marketbtn active" onclick="setRecipeMarket(\'REWE\')">REWE Weilbach</button><button id="rGLOBUS" class="marketbtn" onclick="setRecipeMarket(\'GLOBUS\')">GLOBUS Hattersheim</button><button id="rEDEKA_BUCH" class="marketbtn" onclick="setRecipeMarket(\'EDEKA_BUCH\')">EDEKA Buch Hofheim</button><button id="rEDEKA_HALLER" class="marketbtn" onclick="setRecipeMarket(\'EDEKA_HALLER\')">E center Haller Raunheim</button></div><div class="recipe-controls"><b>Richtung:</b><select id="recipeStyle" onchange="setRecipeStyle(this.value)"><option value="alle">Alle</option><option value="gesund">Gesund</option><option value="leicht">Leicht</option><option value="deftig">Deftig</option><option value="vegetarisch">Vegetarisch</option><option value="schnell">Schnell</option><option value="guenstig">Günstig</option></select></div></div><div id="recipeStatus" class="status"></div><div id="recipeGrid" class="recipe-grid"></div></section>'
new='<section id="recipesView" class="hidden"><div class="recipe-intro"><h2>Rezepte aus aktuellen Angeboten</h2><div class="hint">Die Angebotszutaten stammen aus genau einem Markt. Für vollständige Gerichte werden zusätzlich normale Küchenzutaten ergänzt.</div><div class="household-box"><b>Personen für das Rezept</b><div class="household-grid"><label>Erwachsene<input id="recipeAdults" type="number" min="1" max="12" step="1" value="2" onchange="updateRecipeHousehold()"></label><label>Kinder<input id="recipeChildren" type="number" min="0" max="12" step="1" value="0" onchange="updateRecipeHousehold()"></label><label>Alter der Kinder<select id="recipeChildAge" onchange="updateRecipeHousehold()"><option value="1-3">1–3 Jahre</option><option value="4-6">4–6 Jahre</option><option value="7-9" selected>7–9 Jahre</option><option value="10-12">10–12 Jahre</option><option value="13-14">13–14 Jahre</option><option value="15-18">15–18 Jahre</option></select></label></div><div class="amount-hint">Die Mengen werden an Erwachsene und Kinder angepasst. Dieselbe Haushaltsgröße wird auch für die Einkaufsliste verwendet.</div></div><div class="markets" style="margin-top:12px"><button id="rREWE" class="marketbtn active" onclick="setRecipeMarket(\'REWE\')">REWE Weilbach</button><button id="rGLOBUS" class="marketbtn" onclick="setRecipeMarket(\'GLOBUS\')">GLOBUS Hattersheim</button><button id="rEDEKA_BUCH" class="marketbtn" onclick="setRecipeMarket(\'EDEKA_BUCH\')">EDEKA Buch Hofheim</button><button id="rEDEKA_HALLER" class="marketbtn" onclick="setRecipeMarket(\'EDEKA_HALLER\')">E center Haller Raunheim</button></div><div class="recipe-controls"><b>Richtung:</b><select id="recipeStyle" onchange="setRecipeStyle(this.value)"><option value="alle">Alle</option><option value="gesund">Gesund</option><option value="leicht">Leicht</option><option value="deftig">Deftig</option><option value="vegetarisch">Vegetarisch</option><option value="schnell">Schnell</option><option value="guenstig">Günstig</option></select></div></div><div id="recipeStatus" class="status"></div><div id="recipeGrid" class="recipe-grid"></div></section>'
if old not in s:
    raise SystemExit('recipe section anchor not found')
s=s.replace(old,new,1)

# Keep recipe and shopping household controls synchronized.
s=s.replace("if(v==='recipes')renderRecipes()", "if(v==='recipes'){syncRecipeHouseholdUI();renderRecipes()}", 1)
s=s.replace("function updateHousehold(){household={adults:Math.max(1,Number(houseAdults.value)||1),children:Math.max(0,Number(houseChildren.value)||0),childAge:houseChildAge.value};saveShoppingState();applyShoppingSuggestion()}", "function updateHousehold(){household={adults:Math.max(1,Number(houseAdults.value)||1),children:Math.max(0,Number(houseChildren.value)||0),childAge:houseChildAge.value};saveShoppingState();applyShoppingSuggestion();syncRecipeHouseholdUI();if(!recipesView.classList.contains('hidden'))renderRecipes()}", 1)

start=s.find('function addRecipeToShopping(i)')
end=s.find('function show(id)', start)
if start<0 or end<0:
    raise SystemExit('recipe logic anchors not found')

recipe_code=r'''function syncRecipeHouseholdUI(){if(!document.getElementById('recipeAdults'))return;recipeAdults.value=household.adults;recipeChildren.value=household.children;recipeChildAge.value=household.childAge}
function updateRecipeHousehold(){household={adults:Math.max(1,Number(recipeAdults.value)||1),children:Math.max(0,Number(recipeChildren.value)||0),childAge:recipeChildAge.value};saveShoppingState();syncHouseholdUI();renderRecipes()}
const CHILD_RECIPE_FACTOR={'1-3':.45,'4-6':.6,'7-9':.7,'10-12':.8,'13-14':.9,'15-18':1};
function recipeAdultEquivalents(){return household.adults+household.children*(CHILD_RECIPE_FACTOR[household.childAge]||.7)}
function recipePeopleText(){const a=household.adults,c=household.children,age=household.childAge;return `${a} ${a===1?'Erwachsener':'Erwachsene'}${c?` + ${c} ${c===1?'Kind':'Kinder'} (${age.replace('-', '–')} Jahre)`:''}`}
function scaledRecipeQty(perEq,unit){const raw=Number(perEq||0)*recipeAdultEquivalents();if(unit==='g'||unit==='ml')return Math.max(10,Math.round(raw/10)*10);if(unit==='kg'||unit==='l')return Math.max(.1,Math.round(raw*10)/10);if(unit==='EL'||unit==='TL')return Math.max(.5,Math.round(raw*2)/2);if(unit==='Stück'||unit==='Zehe'||unit==='Bund')return Math.max(1,Math.ceil(raw));return Math.max(.1,Math.round(raw*10)/10)}
function recipeQtyText(perEq,unit){const q=scaledRecipeQty(perEq,unit);return `${String(q).replace('.',',')} ${unit}`}
function addRecipeToShopping(i){const r=lastRecipes[i];if(!r)return;r.items.forEach((p,j)=>{const a=r.needAmounts[j],amount=a?scaledRecipeQty(a.perEq,a.unit):null;addShoppingItemText(productType(p),amount,'type',false,a?.unit||null)});r.extras.forEach(x=>addShoppingItemText(x.name,x.shopQty||1,'auto',false,x.shopUnit||'Packung'));saveShoppingState();renderShopping();setView('shopping')}

function marketItems(){return data.filter(p=>store(p)===recipeMarket)}
function pick(cat,used){return marketItems().filter(p=>category(p)===cat&&!used.has(p.id)).sort((a,b)=>currentPrice(a)-currentPrice(b))[0]}
function recipeAnimalProduct(p){const t=productType(p),c=category(p),text=norm(`${p.name||''} ${p.brand||''}`);if(['Hackfleisch','Rindfleisch','Schweinefleisch','Geflügel','Fisch','Garnelen','Wurst & Aufschnitt'].includes(t))return true;if(['Fleisch','Fisch & Meeresfrüchte'].includes(c))return true;return /\b(hackfleisch|rind|rinder|schwein|schweine|hahnchen|hähnchen|pute|geflugel|geflügel|huhn|hühner|fisch|lachs|forelle|dorade|makrele|matjes|hering|garnele|shrimp|wurst|salami|schinken)\b/.test(text)}
function pickNeed(need,used){let rows=marketItems().filter(p=>!used.has(p.id));if(need.types?.length){rows=rows.filter(p=>need.types.includes(productType(p)));if(!rows.length)return null}else if(need.cats?.length){rows=rows.filter(p=>need.cats.includes(category(p)))}return rows.sort((a,b)=>currentPrice(a)-currentPrice(b))[0]||null}
function renderRecipes(){syncRecipeHouseholdUI();if(!data.length){recipeStatus.textContent='Keine aktuell bestätigten Angebote für Rezepte vorhanden.';recipeGrid.innerHTML='';return}const specs=[
{title:'Fleisch-Gemüse-Pfanne mit Reis',tags:['gesund','leicht','schnell','guenstig'],needs:[{types:['Geflügel','Schweinefleisch','Rindfleisch','Hackfleisch']},{cats:['Gemüse & Salat']}],needAmounts:[{perEq:130,unit:'g'},{perEq:220,unit:'g'}],extras:[{name:'Reis',perEq:75,unit:'g',shopUnit:'g',shopQty:500},{name:'Zwiebeln',perEq:.5,unit:'Stück',shopUnit:'kg',shopQty:.5},{name:'Knoblauch',perEq:.5,unit:'Zehe'},{name:'Öl',perEq:.5,unit:'EL',shopUnit:'Flasche'},{name:'Paprikapulver',perEq:.5,unit:'TL'},{name:'Salz und Pfeffer',perEq:0,unit:'nach Geschmack'}],steps:['Reis nach Packungsangabe garen.','Fleisch in mundgerechte Stücke schneiden und in wenig Öl kräftig anbraten.','Zwiebel, Knoblauch und Gemüse zugeben und bissfest garen.','Mit Paprikapulver, Salz und Pfeffer abschmecken und mit dem Reis servieren.']},
{title:'Fisch mit Ofengemüse und Kartoffeln',tags:['gesund','leicht'],needs:[{types:['Fisch']},{cats:['Gemüse & Salat']}],needAmounts:[{perEq:150,unit:'g'},{perEq:200,unit:'g'}],extras:[{name:'Kartoffeln',perEq:220,unit:'g',shopUnit:'kg',shopQty:1},{name:'Zitrone',perEq:.5,unit:'Stück'},{name:'Olivenöl',perEq:.5,unit:'EL',shopUnit:'Flasche'},{name:'Kräuter',perEq:.5,unit:'TL'},{name:'Salz und Pfeffer',perEq:0,unit:'nach Geschmack'}],steps:['Backofen auf 200 °C vorheizen. Kartoffeln und Gemüse schneiden.','Kartoffeln und Gemüse mit etwas Olivenöl und Kräutern etwa 25 Minuten backen.','Fisch würzen, in den letzten 12–15 Minuten mitgaren.','Mit Zitronensaft abschmecken und gemeinsam anrichten.']},
{title:'Tofu-Gemüse-Wok mit Reis',tags:['gesund','leicht','vegetarisch','schnell'],needs:[{types:['Tofu']},{cats:['Gemüse & Salat']}],needAmounts:[{perEq:140,unit:'g'},{perEq:220,unit:'g'}],extras:[{name:'Reis',perEq:75,unit:'g',shopUnit:'g',shopQty:500},{name:'Sojasauce',perEq:1,unit:'EL',shopUnit:'Flasche'},{name:'Ingwer',perEq:5,unit:'g'},{name:'Knoblauch',perEq:.5,unit:'Zehe'},{name:'Sesam- oder Rapsöl',perEq:.5,unit:'EL',shopUnit:'Flasche'}],steps:['Reis garen. Tofu trocken tupfen und würfeln.','Tofu in wenig Öl rundherum knusprig anbraten und herausnehmen.','Gemüse, Ingwer und Knoblauch kurz und heiß braten.','Tofu zurückgeben, Sojasauce zugeben und mit Reis servieren.']},
{title:'Pasta mit Gemüse und Tomatensauce',tags:['vegetarisch','guenstig','schnell'],needs:[{types:['Pasta & Nudeln'],cats:['Nudeln, Reis & Beilagen']},{cats:['Gemüse & Salat']}],needAmounts:[{perEq:100,unit:'g'},{perEq:180,unit:'g'}],extras:[{name:'Passierte Tomaten',perEq:180,unit:'ml',shopUnit:'Packung'},{name:'Zwiebeln',perEq:.5,unit:'Stück',shopUnit:'kg',shopQty:.5},{name:'Knoblauch',perEq:.5,unit:'Zehe'},{name:'Olivenöl',perEq:.5,unit:'EL',shopUnit:'Flasche'},{name:'Italienische Kräuter',perEq:.5,unit:'TL'},{name:'Salz und Pfeffer',perEq:0,unit:'nach Geschmack'}],steps:['Pasta in Salzwasser bissfest kochen.','Zwiebel und Knoblauch in Olivenöl anschwitzen, Gemüse zugeben.','Passierte Tomaten und Kräuter einrühren und etwa 10 Minuten köcheln.','Pasta unterheben und abschmecken.']},
{title:'Joghurt-Obst-Bowl mit Haferflocken',tags:['gesund','leicht','vegetarisch','schnell'],needs:[{types:['Joghurt & Skyr'],cats:['Molkerei & Käse']},{cats:['Obst']}],needAmounts:[{perEq:180,unit:'g'},{perEq:150,unit:'g'}],extras:[{name:'Haferflocken',perEq:35,unit:'g',shopUnit:'g',shopQty:500},{name:'Nüsse oder Kerne',perEq:15,unit:'g',shopUnit:'Packung'},{name:'Zimt',perEq:.25,unit:'TL'},{name:'Honig',perEq:.5,unit:'TL',shopUnit:'Glas'}],steps:['Joghurt oder Skyr auf Schüsseln verteilen.','Obst waschen, schneiden und daraufgeben.','Haferflocken sowie Nüsse oder Kerne darüberstreuen.','Mit Zimt und nach Wunsch etwas Honig abschließen.']},
{title:'Deftiger Schweinebraten mit Kartoffeln',tags:['deftig'],needs:[{types:['Schweinefleisch'],cats:['Fleisch']},{types:['Kartoffeln'],cats:['Gemüse & Salat']}],needAmounts:[{perEq:180,unit:'g'},{perEq:250,unit:'g'}],extras:[{name:'Zwiebeln',perEq:.75,unit:'Stück',shopUnit:'kg',shopQty:.5},{name:'Brühe',perEq:120,unit:'ml',shopUnit:'Packung'},{name:'Senf',perEq:.5,unit:'TL',shopUnit:'Glas'},{name:'Öl',perEq:.5,unit:'EL',shopUnit:'Flasche'},{name:'Salz und Pfeffer',perEq:0,unit:'nach Geschmack'}],steps:['Fleisch würzen und in einem Bräter kräftig anbraten.','Zwiebeln zugeben, kurz rösten und mit Brühe ablöschen.','Zugedeckt bei mittlerer Hitze schmoren, bis das Fleisch zart ist.','Kartoffeln separat garen; Sauce abschmecken und alles zusammen servieren.']},
{title:'Hackfleisch-Kartoffel-Pfanne mit Paprika',tags:['deftig','guenstig'],needs:[{types:['Hackfleisch']},{types:['Kartoffeln'],cats:['Gemüse & Salat']}],needAmounts:[{perEq:140,unit:'g'},{perEq:230,unit:'g'}],extras:[{name:'Paprika',perEq:.5,unit:'Stück',shopUnit:'kg',shopQty:.5},{name:'Zwiebeln',perEq:.5,unit:'Stück',shopUnit:'kg',shopQty:.5},{name:'Tomatenmark',perEq:15,unit:'g',shopUnit:'Tube'},{name:'Paprikapulver',perEq:.5,unit:'TL'},{name:'Öl',perEq:.5,unit:'EL',shopUnit:'Flasche'},{name:'Salz und Pfeffer',perEq:0,unit:'nach Geschmack'}],steps:['Kartoffeln würfeln und knapp gar vorkochen.','Hackfleisch krümelig anbraten, Zwiebeln und Paprika zugeben.','Tomatenmark kurz mitrösten, Kartoffeln unterheben.','Mit Paprikapulver, Salz und Pfeffer kräftig abschmecken.']},
{title:'Cremige Käse-Pasta mit Erbsen',tags:['deftig','vegetarisch','guenstig'],needs:[{types:['Pasta & Nudeln'],cats:['Nudeln, Reis & Beilagen']},{types:['Käse'],cats:['Molkerei & Käse']}],needAmounts:[{perEq:100,unit:'g'},{perEq:45,unit:'g'}],extras:[{name:'Erbsen',perEq:80,unit:'g',shopUnit:'Packung'},{name:'Milch',perEq:100,unit:'ml',shopUnit:'l',shopQty:1},{name:'Zwiebeln',perEq:.25,unit:'Stück',shopUnit:'kg',shopQty:.5},{name:'Muskat',perEq:.1,unit:'TL'},{name:'Pfeffer',perEq:0,unit:'nach Geschmack'}],steps:['Pasta bissfest kochen; etwas Kochwasser aufheben.','Zwiebel fein würfeln und anschwitzen, Erbsen kurz mitgaren.','Milch erwärmen, Käse darin schmelzen und bei Bedarf mit Kochwasser verdünnen.','Pasta unterheben, mit Muskat und Pfeffer abschmecken.']}
],out=[];for(const spec of specs){if(recipeStyle!=='alle'&&!spec.tags.includes(recipeStyle))continue;const used=new Set(),items=[];for(const need of spec.needs){const p=pickNeed(need,used);if(p&&!(spec.tags.includes('vegetarisch')&&recipeAnimalProduct(p))){items.push(p);used.add(p.id)}}if(items.length===spec.needs.length)out.push({...spec,items})}lastRecipes=out;const marketName=MARKET_NAMES[recipeMarket]||recipeMarket,people=recipePeopleText();recipeStatus.textContent=`${out.length} passende Rezeptvorschläge · Mengen für ${people} · ${recipeStyle==='alle'?'alle Richtungen':recipeStyle==='guenstig'?'günstig':recipeStyle} · Angebotszutaten von ${marketName}`;recipeGrid.innerHTML=out.map((r,i)=>`<article class="recipe"><span class="store ${recipeMarket==='GLOBUS'?'globus':recipeMarket.startsWith('EDEKA_')?'edeka':''}">${marketName}</span><h3>${r.title}</h3><div class="recipe-tags">${r.tags.map(x=>x==='guenstig'?'günstig':x).join(' · ')} · ${people}</div><b>Zutaten aus aktuellen Angeboten:</b><ul>${r.items.map((p,j)=>`<li><b>${recipeQtyText(r.needAmounts[j].perEq,r.needAmounts[j].unit)}</b> ${p.name} · ${euro(currentPrice(p))}</li>`).join('')}</ul><b>Weitere Zutaten:</b><ul>${r.extras.map(x=>`<li>${x.unit==='nach Geschmack'?'nach Geschmack':`<b>${recipeQtyText(x.perEq,x.unit)}</b>`} ${x.name}</li>`).join('')}</ul><b>Zubereitung:</b><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol><button class="recipe-add" onclick="addRecipeToShopping(${i})">🛒 Alle Zutaten auf Einkaufsliste</button></article>`).join('')||`<div class="empty">Aktuell keine passenden Kombinationen für ${marketName} in dieser Richtung.</div>`}
'''
s=s[:start]+recipe_code+s[end:]

p.write_text(s,encoding='utf-8')
print('full household-aware recipes added')
