from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

# CSS fuer klare Preisaufschluesselung
needle=".shop-note{font-size:12px;color:var(--muted);margin-top:10px}"
addition=""".shop-note{font-size:12px;color:var(--muted);margin-top:10px}.shop-totalbox{border:2px solid #d1d5db;border-radius:14px;padding:14px;margin-top:12px;background:#fff}.shop-total-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.shop-total-title{font-size:18px;font-weight:900}.shop-total-price{text-align:right;font-size:28px;font-weight:900;white-space:nowrap}.shop-total-sub{font-size:12px;color:var(--muted);margin-top:3px}.shop-missing{margin-top:10px;padding:9px 10px;border-radius:9px;background:#fff7ed;color:#9a3412;font-size:12px;font-weight:700}.shop-ok{margin-top:10px;padding:9px 10px;border-radius:9px;background:#ecfdf5;color:#047857;font-size:12px;font-weight:700}.cost-table-wrap{overflow-x:auto;margin-top:12px;border:1px solid #e5e7eb;border-radius:11px}.cost-table{width:100%;border-collapse:collapse;min-width:760px;font-size:12px}.cost-table th{background:#f8fafc;text-align:left;padding:9px;border-bottom:1px solid #e5e7eb;white-space:nowrap}.cost-table td{padding:9px;border-bottom:1px solid #eee;vertical-align:top}.cost-table tr:last-child td{border-bottom:0}.cost-table .line-price{text-align:right;font-weight:900;white-space:nowrap}.cost-table .calc{white-space:nowrap}.cost-table .missing-row{background:#fafafa;color:#6b7280}.cost-table .product-small{display:block;color:#6b7280;margin-top:2px;line-height:1.35}.shop-market-list{display:grid;gap:9px;margin-top:14px}.shop-market-detail{border:1px solid #e5e7eb;border-radius:12px;background:#fff;overflow:hidden}.shop-market-detail summary{list-style:none;cursor:pointer;padding:12px 14px;display:flex;justify-content:space-between;gap:14px;align-items:center}.shop-market-detail summary::-webkit-details-marker{display:none}.shop-market-detail summary:before{content:'›';font-size:22px;font-weight:800;transform:rotate(0deg);transition:.15s}.shop-market-detail[open] summary:before{transform:rotate(90deg)}.shop-market-summary-main{flex:1}.shop-market-summary-main b{display:block}.shop-market-summary-main span{font-size:12px;color:var(--muted)}.shop-market-sum{text-align:right;font-size:20px;font-weight:900;white-space:nowrap}.shop-market-sum small{display:block;font-size:10px;color:var(--muted);font-weight:600}.shop-market-body{padding:0 12px 12px}.shop-explain{font-size:12px;color:#4b5563;background:#f8fafc;border-radius:9px;padding:9px;margin-top:10px}@media(max-width:600px){.shop-total-head{display:block}.shop-total-price{text-align:left;margin-top:8px}.cost-table{min-width:680px}.shop-market-detail summary{align-items:flex-start}}"""
if needle not in s:
    raise SystemExit('CSS-Anker nicht gefunden')
s=s.replace(needle,addition,1)

# Komplette Ergebnisdarstellung ersetzen
pattern=r"function shoppingMarketResult\(id\)\{.*?(?=function renderShoppingFast\(\))"
replacement=r'''function shoppingMarketResult(id){const details=shoppingItems.map(item=>{const p=bestShoppingOffer(item,id),count=p?shoppingOfferCount(item,p):0;return{item,p,count}}),found=details.filter(x=>x.p),sum=found.reduce((s,x)=>s+currentPrice(x.p)*x.count,0);return{id,details,found,sum}}
function shoppingLineCost(x){return x.p?currentPrice(x.p)*x.count:0}
function shoppingCalcText(x){if(!x.p)return '—';const unit=purchaseUnitWord(x.item,x.count);return `${x.count} ${unit} × ${euro(currentPrice(x.p))}`}
function shoppingBreakdownTable(details,showMarket=false){return `<div class="cost-table-wrap"><table class="cost-table"><thead><tr><th>Einkaufsliste</th>${showMarket?'<th>Markt</th>':''}<th>Ausgewähltes Angebot</th><th>Bedarf</th><th>Rechnung</th><th style="text-align:right">Positionspreis</th></tr></thead><tbody>${details.map(x=>x.p?`<tr><td><b>${htmlEsc(x.item.text)}</b></td>${showMarket?`<td>${htmlEsc(x.marketName||'')}</td>`:''}<td><b>${htmlEsc(x.p.name)}</b><span class="product-small">${x.p.quantity?`Gebinde: ${htmlEsc(x.p.quantity)}`:'Gebinde nicht angegeben'}</span></td><td>${htmlEsc(formatShoppingAmount(x.item))}</td><td class="calc">${shoppingCalcText(x)}</td><td class="line-price">${euro(shoppingLineCost(x))}</td></tr>`:`<tr class="missing-row"><td><b>${htmlEsc(x.item.text)}</b></td>${showMarket?`<td>${htmlEsc(x.marketName||'—')}</td>`:''}<td>Kein aktuelles Angebot gefunden</td><td>${htmlEsc(formatShoppingAmount(x.item))}</td><td class="calc">—</td><td class="line-price">—</td></tr>`).join('')}</tbody></table></div>`}
function shoppingTotalBox(title,found,total,sum,subline,details,showMarket=false){const missing=total-found;return `<div class="shop-totalbox"><div class="shop-total-head"><div><div class="shop-total-title">${htmlEsc(title)}</div><div class="shop-total-sub">${found} von ${total} Positionen mit aktuellem Angebot${subline?` · ${htmlEsc(subline)}`:''}</div></div><div class="shop-total-price">${euro(sum)}<div class="shop-total-sub">Zwischensumme der gefundenen Angebote</div></div></div>${missing?`<div class="shop-missing">⚠ ${missing} ${missing===1?'Position fehlt':'Positionen fehlen'} und ${missing===1?'ist':'sind'} in dieser Summe nicht enthalten.</div>`:`<div class="shop-ok">✓ Alle Positionen wurden als aktuelles Angebot gefunden.</div>`}<div class="shop-explain">So entsteht die Summe: Für jede gefundene Position wird die benötigte Zahl an Packungen/Kästen mit dem Angebotspreis multipliziert. Nicht gefundene Positionen zählen mit 0 € und werden ausdrücklich als fehlend markiert.</div>${shoppingBreakdownTable(details,showMarket)}</div>`}
function renderShoppingResults(force=false){if(!shoppingItems.length){shoppingResults.innerHTML='<div class="empty">Füge zuerst Produkte oder Produktarten hinzu.</div>';return}const ids=[...selectedShoppingMarkets];if(!ids.length){shoppingResults.innerHTML='<div class="empty">Wähle mindestens einen Markt aus.</div>';return}if(!force){shoppingResults.innerHTML='<button class="shop-add" onclick="renderShoppingResults(true)">Preise vergleichen</button><div class="shop-note">Die Einkaufsliste wird zuerst vollständig erstellt. Erst danach wird der Angebotsvergleich berechnet.</div>';return}
const results=ids.map(shoppingMarketResult).sort((a,b)=>b.found.length-a.found.length||a.sum-b.sum);
const combo=shoppingItems.map(item=>{const opts=ids.map(id=>({id,p:bestShoppingOffer(item,id)})).filter(x=>x.p).sort((a,b)=>currentPrice(a.p)*shoppingOfferCount(item,a.p)-currentPrice(b.p)*shoppingOfferCount(item,b.p));const best=opts[0]||null;return{item,best,p:best?best.p:null,count:best?shoppingOfferCount(item,best.p):0,marketName:best?MARKET_NAMES[best.id]:'—'}}),comboFound=combo.filter(x=>x.p),comboSum=comboFound.reduce((s,x)=>s+shoppingLineCost(x),0),comboMarkets=[...new Set(comboFound.map(x=>x.marketName))];
const best=shoppingTotalBox('Günstigste Kombination der aktuellen Angebote',comboFound.length,shoppingItems.length,comboSum,comboMarkets.join(' + '),combo,true);
const marketDetails=`<div class="shop-market-list"><h4 style="margin:4px 0 0">Einzelne Märkte</h4>${results.map(r=>{const missing=shoppingItems.length-r.found.length;return `<details class="shop-market-detail"><summary><div class="shop-market-summary-main"><b>${MARKET_NAMES[r.id]}</b><span>${r.found.length}/${shoppingItems.length} gefunden${missing?` · ${missing} fehlen`:''}</span></div><div class="shop-market-sum">${euro(r.sum)}<small>Zwischensumme</small></div></summary><div class="shop-market-body"><div class="shop-explain">Diese Summe enthält nur die ${r.found.length} gefundenen Angebotspositionen. ${missing?`${missing} ${missing===1?'fehlende Position ist':'fehlende Positionen sind'} nicht eingerechnet.`:'Alle Positionen sind enthalten.'}</div>${shoppingBreakdownTable(r.details,false)}</div></details>`}).join('')}</div>`;
shoppingResults.innerHTML=best+marketDetails+`<div class="shop-note"><b>Noch kein vollständiger Kassenbon:</b> Reguläre Ladenpreise für Artikel ohne aktuelles Angebot fehlen weiterhin. Deshalb nennen wir die angezeigten Beträge bewusst Zwischensummen.</div>`}
'''
ns,n=re.subn(pattern,lambda m: replacement,s,count=1,flags=re.S)
if n!=1:
    raise SystemExit(f'Ergebnisblock nicht eindeutig gefunden: {n}')
s=ns
p.write_text(s,encoding='utf-8')
print('Preiszusammenfassung neu gestaltet')
